title: My first lesson
description: How to upload a image
template:
  repo: my-first-lesson-template
  name: my-first-lesson
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
